services:
  monolith:
    build: .
    ports:
      - "5000:5000"  # API Gateway
      - "5001:5001"  # User Service V1
      - "5002:5002"  # User Service V2
      - "5003:5003"  # Order Service
    environment:
      - MONGODB_URI=mongodb+srv://mongo:ipW272wjb1fwWRSi@cluster0.efff1.mongodb.net/?retryWrites=true&w=majority
      - PYTHONUNBUFFERED=1
      - RABBITMQ_HOST=rabbitmq
    volumes:
      - ./config.ini:/app/config.ini
    depends_on:
      - rabbitmq

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest